<?php

use Drupal\commerce_tax\Entity\TaxType;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_mail().
 */
function iq_commerce_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
  \Drupal::logger('iq_commerce')->notice($key);
  mb_internal_encoding("UTF-8");
  $message['subject'] = mb_encode_mimeheader($message['subject'],'UTF-8','Q');
}
/**
 * Implements hook_theme().
 */
function iq_commerce_theme($existing, $type, $theme, $path) {
  return [
    'commerce_order_receipt' => [
      'template' => 'iq-commerce-order-receipt',
      'base hook' => 'commerce_order_receipt',
    ],
    'dropdown_cart_block' => [
      'variables' => [
        'count_text' => NULL,
        'url' => NULL,
        'count' => NULL,
        'content' => NULL,
        'links' => NULL
      ]
    ]
  ];
}

/**
 * Implements hook_views_data_alter().
 */
function iq_commerce_views_data_alter(array &$data) {
  $data['views']['alter_cart_quantity_field'] = [
    'title' => t('Quantity edit form'),
    'help' => t('Form to alter the quantity of a cart item'),
    'field' => [
      'id' => 'alter_cart_quantity_field',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function iq_commerce_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Add the tax rate for each product type.
  if ($form_id == 'commerce_product_type_edit_form') {
    $tax_type = \Drupal::service('plugin.manager.commerce_tax_type')->createInstance('swiss_vat');
    $zones = $tax_type->getZones();
    /** @var \Drupal\commerce_tax\TaxZone $zone */
    $zone = reset($zones);
    $rates = $zone->getRates();
    $rate_labels = [];
    foreach ($rates as $rate) {
      $rate_labels[$rate->getId()] = $rate->getLabel() . ' - ' . $rate->getPercentage()->toString();
    }
    /** @var \Drupal\commerce_product\Entity\ProductType $product_type_entity */
    $product_type_entity = $form_state->getFormObject()->getEntity();
    if (!empty($product_type_entity)) {
      $default_tax_rate = $product_type_entity->getThirdPartySetting('iq_commerce', 'tax_rate');
      $form['tax_rate'] = [
        '#type' => 'select',
        '#title' => t('Tax Rate'),
        '#options' => $rate_labels,
        '#default_value' => $default_tax_rate
      ];
    }

    $form['actions']['submit']['#submit'][] = 'iq_commerce_product_type_form_submit';
  }
}

function iq_commerce_product_type_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  /** @var \Drupal\commerce_product\Entity\ProductType $product_type_entity */
  $product_type_entity = $form_state->getFormObject()->getEntity();
  $product_type_entity->setThirdPartySetting('iq_commerce',  'tax_rate', $form_state->getValue('tax_rate'));
  $product_type_entity->save();
}

/**
 * Implements hook_views_pre_render().
 */
function iq_commerce_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'variant_catalog') {
    \Drupal::logger('iq_commerce')->notice('STIGNAVME VO HOOKOT');

    // Array of nodes to prevent duplicates.
    $variation_ids = [];
    // Manipulated results.
    $resultNoDoubleNodes = [];
    $i = 0;
    // Check each node of the result array on it's nid.
    foreach ($view->result as $row) {

      $variation_id = $row->commerce_product_variation_field_data_commerce_product__vari_1;
      // If this node isn't a duplicate.
      if (!in_array($variation_id, $variation_ids)) {
        $row->index = $i;
        $i++;
        // Add it to the manipulated results.
        $resultNoDoubleNodes[] = $row;
        // Mark this nid as in results to prevent duplicates from now on.
        $variation_ids[] = $variation_id;
      }
    }
    // Replace the old results with the results without duplicates.
    $view->result = $resultNoDoubleNodes;

  }
}
