# Schema for the configuration files of the iq_commerce module.
iq_commerce.settings:
  type: config_object
  label: 'iQual Commerce settings'
  mapping:
    header:
      type: text_format
      label: 'Header'
    footer:
      type: text_format
      label: 'Footer'
    cart_header:
      type: label
      label: 'Cart Header'
    cart_header_size:
      type: label
      label: 'Cart Header Size'

