<?php

/**
 * Implements hook_form_alter().
 */
function iq_commerce_order_additional_fields_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
  // Only show collection date if the customer has selected
  // the option to pick up product(s) from store.
  if ($form_id == 'commerce_checkout_flow_multistep_default' && !empty($form['collection_date_pane']) && !empty($form['shipping_information'])) {
    $shipping_methods = $form['shipping_information']['shipments'][0]['shipping_method']['widget'][0]['#options'] ?? [];
    /** @var \Drupal\Component\Render\FormattableMarkup $shipping_method */
    foreach ($shipping_methods as $key => $shipping_method) {
      $label = explode(':', $shipping_method->jsonSerialize())[0];
      // @TODO The label should be configurable, since the shipping method
      // @TODO might be named something else.
      if ($label == 'Abholung vor Ort') {
        $form['collection_date_pane']['collection_date']['#states'] = [
          'visible' => [
            ':input[name="shipping_information[shipments][0][shipping_method][0]"]' => ['value' => $key],
          ],
          'required' => [
            ':input[name="shipping_information[shipments][0][shipping_method][0]"]' => ['value' => $key],
          ],
        ];
      }
    }
  }
}
